/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package com.sitesdoarthur.teste;

import static com.sitesdoarthur.teste.PrimaryController.valorr;
import java.awt.List;

/**
 *
 * @author arthur
 */
public class Menu extends javax.swing.JFrame {

    private boolean fecha = false;
    private boolean config = false;
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgCoder = new javax.swing.JDialog();
        btnAdicionar = new java.awt.Button();
        btnRemover = new java.awt.Button();
        label1 = new java.awt.Label();
        list1 = new java.awt.List();
        textArea1 = new java.awt.TextArea();
        dlgConfig = new javax.swing.JDialog();
        fleAbreFecha = new javax.swing.JFileChooser();
        btnCoder = new javax.swing.JButton();
        btnConfig = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        dlgCoder.setTitle("HTML Coder");
        dlgCoder.setBounds(new java.awt.Rectangle(0, 0, 500, 500));

        btnAdicionar.setLabel("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        dlgCoder.getContentPane().add(btnAdicionar, java.awt.BorderLayout.LINE_START);

        btnRemover.setLabel("Remover");
        dlgCoder.getContentPane().add(btnRemover, java.awt.BorderLayout.LINE_END);

        label1.setText("Selecione o item para adiciona-lo ou remove-lo de seu código");
        dlgCoder.getContentPane().add(label1, java.awt.BorderLayout.PAGE_START);
        dlgCoder.getContentPane().add(list1, java.awt.BorderLayout.CENTER);

        textArea1.setEditable(false);
        dlgCoder.getContentPane().add(textArea1, java.awt.BorderLayout.PAGE_END);

        setTitle("Meu principal do CODER");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        btnCoder.setText("Abrir HTMLCoder");
        btnCoder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoderActionPerformed(evt);
            }
        });
        getContentPane().add(btnCoder, java.awt.BorderLayout.LINE_START);

        btnConfig.setText("Configuraçoes");
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfig, java.awt.BorderLayout.LINE_END);

        jButton1.setText("Inserir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.out.print("saindo");
    }//GEN-LAST:event_exitForm

    private void btnCoderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoderActionPerformed

        if(fecha == false){
            fecha = true;
            dlgCoder.setVisible(true);
        } else {
            fecha = false;
            dlgCoder.setVisible(false);
        }
    }//GEN-LAST:event_btnCoderActionPerformed

    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        if(config == false) {
            dlgConfig.setVisible(true);
            config = true;
        } else {
            dlgConfig.setVisible(false);
            config = false;
        }
    }//GEN-LAST:event_btnConfigActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        valorr = textArea1.getText();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }
    
    public void init() {
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
        initComponents();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAdicionar;
    private javax.swing.JButton btnCoder;
    private javax.swing.JButton btnConfig;
    private java.awt.Button btnRemover;
    private javax.swing.JDialog dlgCoder;
    private javax.swing.JDialog dlgConfig;
    private javax.swing.JFileChooser fleAbreFecha;
    private javax.swing.JButton jButton1;
    private java.awt.Label label1;
    private java.awt.List list1;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
